WIP: Added TF and PyTorch classification conversion cases
opencv/opencv pull request #17604
Opened 2020-06-21 21:19 UTC by LupusSanctus

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under OpenCV (BSD) License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

2020-07-10 09:11 UTC, AnnaPetrovicheva commented on samples/python/tutorial_code/dnn/dnn_conversion/common/accuracy_eval.py
> +            # changed to os.path.join
@LupusSanctus let's remove the comment?

2020-07-10 09:12 UTC, AnnaPetrovicheva commented on samples/python/tutorial_code/dnn/dnn_conversion/common/accuracy_eval.py
> +            cols = img.shape[1]
I suggest `rows, cols, _ = img.shape`

2020-07-10 09:15 UTC, AnnaPetrovicheva commented on samples/python/tutorial_code/dnn/dnn_conversion/common/accuracy_eval.py
> +            image_data = img[:, :, 0:3].transpose(2, 0, 1)
I suggest to split this code to several small functions like `center_crop` and `preprocess_image` to make it more readable.

2020-07-10 09:15 UTC, AnnaPetrovicheva commented on samples/python/tutorial_code/dnn/dnn_conversion/common/accuracy_eval.py
> +    def __init__(self, imgs_dir, frame_size, bgr_to_rgb):
It would be good to declare the expected argument types in the signature.

2020-07-10 09:16 UTC, AnnaPetrovicheva commented on samples/python/tutorial_code/dnn/dnn_conversion/common/accuracy_eval.py
> +        self.mean_blob *= 117
What is 117? Looks like a magic number - let's avoid them.

2020-07-10 09:19 UTC, AnnaPetrovicheva commented on samples/python/tutorial_code/dnn/dnn_conversion/requirements.txt
> +opencv==4.3.0
I don't think we can do this. @asmorkalov please take a look.

2020-07-10 09:20 UTC, AnnaPetrovicheva commented on samples/python/tutorial_code/dnn/dnn_conversion/tf/classification/py_to_py_resnet50.py
> +    print(layers)
Do we need this output?

2020-07-10 09:21 UTC, AnnaPetrovicheva commented on samples/python/tutorial_code/dnn/dnn_conversion/tf/tf_model.py
> +        out = self._prepared_model(batch_tf)[..., 1:1001]
Would be better to change the indices to `1:self.num_classes + 1`.

2020-08-31 17:27 UTC, alalek reviewed
Need to clarify licensing terms of used images.

2020-08-31 17:27 UTC, alalek commented on doc/tutorials/dnn/dnn_pytorch_tf_classification/pytorch_cls_model_conversion_tutorial.md
> +Let's briefly view the key concepts involved in the pipeline of PyTorch models transition with OpenCV API. The initial step in conversion of PyTorch models into [cv.dnn_Net](https://docs.opencv.org/4
> https://docs.opencv.org/4.3.0/

Please remove such links from the document.
Doxygen reference should be used instead

2020-08-31 17:27 UTC, alalek commented on samples/dnn/common.py
> +                                   'variable or pass a full path to model.')
Please avoid unnecessary changes

2020-08-31 17:27 UTC, alalek commented on samples/dnn/common.py
> +    add_argument(zoo, parser, 'rgb', type=bool, default=True,
> default=True

Breaking change

2020-09-04 12:56 UTC, asmorkalov requested changes

2020-09-04 12:56 UTC, asmorkalov commented on samples/dnn/dnn_model_runner/dnn_conversion/requirements.txt
> +torch>=1.7.0.dev20200727
```
Double requirement given: torch>=1.7.0.dev20200727 (from -r ./requirements.txt (line 15)) (already in torch>=1.5.1 (from -r ./requirements.txt (line 5)), name='torch')
```

2020-09-04 12:56 UTC, asmorkalov commented on doc/tutorials/dnn/dnn_pytorch_tf_classification/tf_cls_model_conversion_tutorial.md
> +# obtainTF model predictions
space is missing.

2020-09-04 12:56 UTC, asmorkalov commented on samples/dnn/dnn_model_runner/dnn_conversion/requirements.txt
> +torch>=1.7.0.dev20200727
Is there any reason to use non-stable PyTorch version?

2020-09-04 12:56 UTC, asmorkalov commented on samples/dnn/dnn_model_runner/dnn_conversion/requirements.txt
> +torchvision>=0.8.0.dev20200727
`dataclasses` module is missing for Python distros before 3.7.

2020-11-24 11:10 UTC, asmorkalov commented
There is conflict in `requirements.txt`. Pip reports:
```
ERROR: Double requirement given: torch>=1.7.0.dev20200727 (from -r ./requirements.txt (line 15)) (already in torch>=1.5.1 (from -r ./requirements.txt (line 5)), name='torch')
```

2020-11-24 11:11 UTC, asmorkalov commented
Please add bock with setup instructions. Let's expect that user already have python3 and pip installed.

2020-11-24 12:02 UTC, asmorkalov requested changes

2020-11-24 12:04 UTC, asmorkalov commented
@LupusSanctus Sorry for confusion, please ignore the `requirements.txt` issue. I used old version of the code. Please remove OpenCV package from `requirements.txt` and add line to tutorial or just leave OpenCV without version. 4.5.x is not available with pip now.

2020-12-04 18:11 UTC, alalek commented
Please rebase commits to resolve merge conflicts.

2020-12-10 22:34 UTC, LupusSanctus commented
@asmorkalov, setup instructions were added in tutorial `Requirements`  section. Also `requirements.txt` was corrected.

2020-12-18 08:36 UTC, alalek commented
Is this PR in WIP status?

2020-12-20 08:04 UTC, alalek reviewed
Well done!

Please take a look on minor comments below.

2020-12-22 08:52 UTC, ichisadashioko commented on doc/tutorials/dnn/dnn_pytorch_tf_classification/tf_cls_model_conversion_tutorial.md
> +Therefore, to reproduce the image preprocessing pipeline from the TF [``mobilenet.preprocess_input``](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/mobilen
Here is the permalink - `https://github.com/tensorflow/tensorflow/blob/02032fb477e9417197132648ec81e75beee9063a/tensorflow/python/keras/applications/mobilenet.py#L443-L445`.

2021-01-02 12:25 UTC, asmorkalov requested changes

2021-01-02 12:25 UTC, asmorkalov commented on doc/tutorials/dnn/dnn_pytorch_tf_classification/tf_cls_model_conversion_tutorial.md
> +For OpenCV-Python building from source, follow the corresponding instructions from the [OpenCV-Python tutorial section](https://docs.opencv.org/master/da/df6/tutorial_py_table_of_contents_setup.html)
Please use Doxygen @ref here instead of direct link.

2021-01-02 12:25 UTC, asmorkalov commented on doc/tutorials/dnn/dnn_pytorch_tf_classification/tf_cls_model_conversion_tutorial.md
> +Before you start the installation of the libraries, you can customize the [requirements.py](https://github.com/opencv/opencv/tree/master/samples/dnn/dnn_model_runner/dnn_conversion/requirements.txt),
`requirements.txt` in link.

2021-01-02 12:25 UTC, asmorkalov commented on samples/dnn/classification.py
> +                cv.dnn.DNN_BACKEND_OPENCV)
CuDNN?

2021-01-02 12:25 UTC, asmorkalov commented on samples/dnn/classification.py
> +            blob[0] /= np.asarray(args.std, dtype=np.float32).reshape(3, 1, 1)
Please add check to exclude devision by zero as in C++ version.

2021-01-02 12:25 UTC, asmorkalov commented on samples/dnn/dnn_model_runner/dnn_conversion/common/img_utils.py
> +    img /= [0.229, 0.224, 0.225]
The same values are in `default_preprocess_config.py`. Let's reuse the constants.

2021-01-18 09:15 UTC, asmorkalov commented
@LupusSanctus Friendly reminder.

2021-01-26 08:45 UTC, asmorkalov approved these changes

2021-01-26 11:04 UTC, alalek approved these changes
Well done! Thank you :+1:

2021-01-26 11:06 UTC, merged