Update the stereo sample:
opencv/opencv pull request #18129
Opened 2020-08-18 14:14 UTC by pemmanuelviel

* add the HH4 mode
* option to display disparity with a color map
* display current settings in the title bar
* don't close app when wanting to take screenshots

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

2020-08-19 09:04 UTC, mshabunin commented on samples/cpp/stereo_match.cpp
> +        if (color_display) {
Please use consistent formatting across the file:
```.cpp
if (...)
{
    ...
}
```

2020-08-20 07:43 UTC, asmorkalov requested changes

2020-08-20 07:43 UTC, asmorkalov commented on samples/cpp/stereo_match.cpp
>          imwrite(disparity_filename, disp8);
`--color` option handling is missed here.

2020-08-20 07:53 UTC, mshabunin approved these changes

2020-08-20 08:48 UTC, pemmanuelviel commented
It's on purpose.
Datasets are giving ground truth on one channel (8 or more bits that can be
converted to 8 bits). Storing the image on one channel also allows direct
comparison with these ground truths, knowing in addition that the choice of
the color map might not be the same one from one dataset to another one
when used for display.
If we want to store color mapped disparity images for visual comparison,
screenshot is an option as it keeps track in the title bar of the different
settings used for the process.
Are you fine with that?


Le jeu. 20 août 2020 à 09:43, Alexander Smorkalov <notifications@github.com>
a écrit :

> *@asmorkalov* requested changes on this pull request.
> ------------------------------
>
> In samples/cpp/stereo_match.cpp
> <https://github.com/opencv/opencv/pull/18129#discussion_r473708275>:
>
> > @@ -268,19 +274,6 @@ int main(int argc, char** argv)
>          disp.convertTo(disp8, CV_8U, 255/(numberOfDisparities*16.));
>      else
>          disp.convertTo(disp8, CV_8U);
> -    if( !no_display )
> -    {
> -        namedWindow("left", 1);
> -        imshow("left", img1);
> -        namedWindow("right", 1);
> -        imshow("right", img2);
> -        namedWindow("disparity", 0);
> -        imshow("disparity", disp8);
> -        printf("press any key to continue...");
> -        fflush(stdout);
> -        waitKey();
> -        printf("\n");
> -    }
>
>      if(!disparity_filename.empty())
>          imwrite(disparity_filename, disp8);
>
> --color option handling is missed here.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/opencv/opencv/pull/18129#pullrequestreview-471342031>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABPELVIX756VKRDQDE4PCX3SBTH2PANCNFSM4QDRHNBA>
> .
>

2020-08-20 09:34 UTC, asmorkalov commented
The default behavior is to produce one channel disparity image. It works with datasets as you expect. I just propose to have the consistent option behavior for case with window and in "no-display" mode. It can be used for testing.

2020-08-20 11:43 UTC, asmorkalov approved these changes
:+1:

2020-08-20 13:22 UTC, merged