videoio/gstreamer: Add support for GRAY16_LE.
opencv/opencv pull request #18694
Opened 2020-10-29 11:59 UTC by zyp

This patch adds 16-bit grayscale support to GStreamerCapture and updates the test with 16-bit support and a 16-bit test case.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

2020-10-29 12:28 UTC, zyp commented
I missed this before I started, but I see now that this is a duplicate of #14035. What would it take to get either of these merged?

2020-11-26 18:00 UTC, mshabunin commented
@zyp , the test fails on my machine, looks like only part of frame is returned.

@alalek , do we have a configuration on buildbot with GStreamer enabled?

2020-11-26 19:10 UTC, zyp commented
Hi, I can look into the test if you can post the log of how it is failing. I'm pretty sure it was passing here, so I'd like to get an idea of what's going on before I spend time trying to reproduce your result.

I looked through the buildbot logs, and GStreamer is disabled in both the Linux x64 and the Linux32 build, and I guess none of the other configs are likely to have it either, so it's a reasonable assumption that buildbot didn't run the relevant test.

2020-11-26 19:36 UTC, mshabunin commented
@zyp , it is reproducible only in plugin-mode: `-DVIDEOIO_PLUGIN_LIST=gstreamer` cmake option.

2020-11-26 19:49 UTC, zyp commented
Ah, that makes sense.

How should we go about solving this? Would it suffice to disable the 16-bit test in plugin mode for now and leave that as unsupported, or should I take a look at improving the plugin-backend to support 16-bit?

2021-02-18 18:19 UTC, joshdoe commented
Just mentioning #19320 to link this.

2021-04-08 23:03 UTC, asenyaev commented
jenkins cn please retry a build

2021-08-06 12:49 UTC, mshabunin commented
@zyp, I've updated your PR. If possible please check if it works in your scenarios.

2021-08-11 19:31 UTC, mshabunin commented
I've also added `BGRx` format support (resolve #11059).
@alalek , please take a look.

2021-08-12 08:10 UTC, alalek approved these changes
Looks good to me :+1:

2021-08-12 11:02 UTC, alalek requested changes
Please take a look on GStreamer tests.
Looks like there are several failures due to changed output types

2021-08-12 11:37 UTC, alalek commented on modules/videoio/src/cap_gstreamer.cpp
> +    caps.attach(gst_caps_from_string("video/x-raw, format=(string){BGR, BGRA, RGBA, BGRx, RGBx, GRAY8, GRAY16_LE, GRAY16_BE}; video/x-bayer,format=(string){rggb,bggr,grbg,gbrg}; image/jpeg"));
Perhaps this should be changed for "manual" pipelines only.

2021-08-16 11:02 UTC, alalek approved these changes

2021-08-16 16:20 UTC, merged