Add live timestamps to MSMF Video API
opencv/opencv pull request #18966
Opened 2020-11-30 05:26 UTC by Staticity

When using `cv::VideoCapture` by index on Windows with MS Media Foundation (`cv::CAP_MSMF`), the field `cv::CAP_PROP_POS_MSEC` always returns 0.

This PR makes an unused timestamp parameter from the `IMFSourceReaderCallback::OnReadSample(...)` interface available through `cv::VideoCapture::get(cv::CAP_PROP_POS_MSEC)`.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

2020-11-30 08:58 UTC, asmorkalov commented
@Staticity Thanks for the contribution! It looks like we do not have test for `cv::CAP_PROR_FRAME_MSEC` option at al. I added general test for all back-ends in `https://github.com/opencv/opencv/pull/18968`. Let's merge the test first and the we cane check your solution and merge it too.

2020-12-01 08:27 UTC, asmorkalov requested changes
@Staticity My patch with `CAP_PROP_POS_MSEC` has been merged. Please rebase your brunch on top of current 3.4 and remove Media Foundation check in test code to active test for MSMF back-end too.

2020-12-01 09:27 UTC, Staticity commented
@asmorkalov Ignore the faulty latest push(es). Sounds good, I'm rebased on 3.4 and building the tests now.

I left a comment on your merged PR for the additional test. Does it also test VideoCapture by index? It seems that the VideoCapture is opened with a filepath instead of device index -- so I'm unsure if that test will actually test this code.

2020-12-01 09:40 UTC, alalek commented
> Does it also test VideoCapture by index

We usually don't have such tests in regular OpenCV testing scope (due to specific requirements).

However it would be nice to add some "manual" test here: https://github.com/opencv/opencv/blob/3.4.12/modules/videoio/test/test_camera.cpp

(check usage note in mentioned file)

2020-12-01 10:31 UTC, asmorkalov commented
The patch looks good to me. Please squeeze commits to merge the code. Also it'll be great if you add disabled test for cameras in the way as alalek proposed.

2020-12-02 08:05 UTC, asmorkalov requested changes
Please add the same check to `TEST(DISABLED_VideoIO_Camera, validate_V4L2_MJPEG)`.

2020-12-02 08:05 UTC, asmorkalov commented on modules/videoio/test/test_camera.cpp
> +    const double framePeriod = 1. / capture.get(cv::CAP_PROP_FPS);
I prpose to check returned FPS value if it's not zero before division.

2020-12-02 15:26 UTC, asmorkalov commented
@Staticity Please squash commits after fix.

2020-12-03 07:59 UTC, asmorkalov approved these changes
Looks good to me :+1:

2020-12-03 09:33 UTC, Staticity commented
Wonderful, thanks for the help!

2020-12-03 10:56 UTC, alalek approved these changes
Thank you for contribution!

2020-12-03 10:57 UTC, merged