Fix Darwin collision of Point/Rect/Size types
opencv/opencv pull request #18977
Opened 2020-12-01 01:29 UTC by chrisballinger

Splitting this out into a standalone PR, based on the initial work here: https://github.com/opencv/opencv/pull/18925

This patch prevents a symbol conflict between types `Point`/`Rect`/`Size` and those provided by `Darwin`:

```
/Users/chrisbal/Documents/opencv/.build/x86_64-apple-macosx/debug/opencv2.framework/Modules/opencv2.swiftmodule/x86_64-apple-macos.swiftinterface:676:81: error: ambiguous type name 'Rect' in module 'opencv2'
  public func detectMultiScale(img: opencv2.Mat, foundLocations: inout [opencv2.Rect], foundWeights: inout [Swift.Double], hitThreshold: Swift.Double)
                                                                        ~~~~~~~ ^
opencv2.Rect:1:12: note: found candidate with type 'Rect'
open class Rect : NSObject {
           ^
Darwin.Rect:1:15: note: found candidate with type 'Rect'
public struct Rect {
```

I provided backwards compatibility typealiases, which are used by the existing test suite.

This doesn't attempt to solve https://github.com/opencv/opencv/issues/18843, which is still a problem, but would be a bigger undertaking.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

2020-12-01 08:33 UTC, asmorkalov commented
@vpisarev Could you take a look?

2020-12-01 09:51 UTC, alalek commented
/cc @komakai

2020-12-01 11:13 UTC, komakai commented
As per my previous comment on #18843 my preferred way to solve this is to mark the Swift extensions that use these types as @nonobjc
like this:
https://github.com/komakai/opencv/commit/aa949df305ef360aeb660783fcc1000a3d9a8e17

Note - there is no name clash in Swift only in Objective-C

2020-12-01 11:16 UTC, komakai requested changes
This is a breaking change. Please consider a non-breaking change like in: https://github.com/komakai/opencv/commit/aa949df305ef360aeb660783fcc1000a3d9a8e17

2020-12-01 19:24 UTC, chrisballinger commented
@komakai I've removed the other changes from this PR and cherry-picked https://github.com/komakai/opencv/commit/aa949df305ef360aeb660783fcc1000a3d9a8e17 as you suggested.

2020-12-01 23:32 UTC, komakai commented
> @komakai I've removed the other changes from this PR and cherry-picked [komakai@aa949df](https://github.com/komakai/opencv/commit/aa949df305ef360aeb660783fcc1000a3d9a8e17) as you suggested.

Thanks!

2020-12-02 19:06 UTC, alalek approved these changes

2020-12-02 19:07 UTC, merged