Use nvenc
opencv/opencv pull request #19309
Opened 2021-01-12 05:14 UTC by JoshuaJakowlew

Allow nvenc encoder for h264 codec via ffmpeg library.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

2021-01-12 08:31 UTC, asmorkalov requested changes
The patch reverts several useful features like orientation metadata handling and introduce a lot of changes that are not related to NVIDIA hardware encoder support. Could you reduce the PR and bring only focused patch with NVIDIA encoder only?

2021-01-12 08:31 UTC, asmorkalov commented on modules/videoio/src/cap_ffmpeg_impl.hpp
> -    void rotateFrame(cv::Mat &mat) const;
The logic related to frame rotation and orientation metadata should be restored.

2021-01-12 08:31 UTC, asmorkalov commented on modules/videoio/src/cap_ffmpeg_impl.hpp
> +        if (avdiscard_entry != 0) {
No need to change it.

2021-01-12 08:38 UTC, asmorkalov requested changes

2021-01-12 08:38 UTC, asmorkalov commented on modules/videoio/src/cap_ffmpeg_impl.hpp
> +#if LIBAVCODEC_VERSION_INT < ((52<<16)+(123<<8)+0)
`CALC_FFMPEG_VERSION`?

2021-01-12 09:01 UTC, VadimLevin requested changes
Please, rebase to the latest version of the target branch - you are overriding changes that were made by other contributors.

2021-01-20 08:35 UTC, asmorkalov commented
@JoshuaJakowlew Friendly reminder.

2021-01-25 17:36 UTC, asmorkalov commented
@JoshuaJakowlew Do you have a chance to look on remarks and fix them?

2021-01-29 11:22 UTC, asmorkalov commented
@JoshuaJakowlew I tried to re-base you PR with Git and it's not rebase issue. Please re-fresh your implementation manually and remove irrelevant changes.

2021-02-04 10:46 UTC, asmorkalov commented
@JoshuaJakowlew Friendly reminder.

2021-02-04 22:20 UTC, JoshuaJakowlew commented
> 
> 
> @JoshuaJakowlew Friendly reminder.

So sorry for long inactivity. I removed optinal code. Originally, I used version from vcpkg, bloating code was from their version

2021-02-05 07:29 UTC, asmorkalov commented
Related patch: https://github.com/opencv/opencv/pull/19460

2021-02-05 07:33 UTC, asmorkalov requested changes
Thanks a lot for the patch. Could you look at related work for hardware acceleration support for video codecs on Intel hardware. I propose to wait a bit when the patch will be merged and accommodate to the new solution. It brings extra options to VideoWriter contrstructor and it should be used to select proper hardware backend.

2021-02-05 07:33 UTC, asmorkalov commented on modules/videoio/src/cap_ffmpeg_impl.hpp
> +        c->bit_rate = 4000000;
hardcoded bit rate is bad idea.

2021-02-05 14:03 UTC, JoshuaJakowlew commented
Should I try to merge with pinned patch, or try to add Intel hw support by myself?

2021-02-05 14:52 UTC, asmorkalov commented
No, let's wait a bit till the related patch is merged to master to reduce conflicts.

2021-03-03 09:09 UTC, asmorkalov commented
@JoshuaJakowlew Related patch for hardware codecs support in FFmpeg has been merged. Please go ahead and rebase your patch.

2021-03-12 08:51 UTC, asmorkalov commented
@JoshuaJakowlew Friendly reminder.

2021-03-19 06:05 UTC, asmorkalov commented
@JoshuaJakowlew Friendly reminder.

2023-01-16 09:25 UTC, mshabunin commented
I believe HW decoding support has been covered by #19460, so this PR can be closed. Feel free to comment and reopen if this is not the case.

2023-01-16 09:25 UTC, closed without merging