Suppression list for the build using Valgrind on ARM
opencv/opencv pull request #20303
Opened 2021-06-23 16:35 UTC by asenyaev

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### Description
This PR solves issues with leaks and uninitialized values on ARM.

2021-06-24 09:23 UTC, asenyaev commented
jenkins cn please retry a build

2021-07-06 10:34 UTC, asmorkalov requested changes
The PR has been discussed off-line.

2021-07-14 07:37 UTC, asenyaev commented on platforms/scripts/valgrind_3rdparty_arm.supp
> +   fun:vld1q_dup_u32
Removed it and keep only a function `png_do_expand_palette_rgb8_neon`.

2021-07-14 07:37 UTC, asenyaev commented on platforms/scripts/valgrind_3rdparty_arm.supp
> +   fun:vld3_dup_u8
Removed it and keep only a function `png_do_expand_palette_rgb8_neon`.

2021-07-14 07:43 UTC, asenyaev commented on platforms/scripts/valgrind_3rdparty_arm.supp
> +}
I found that these 3 suppressions are used in different places in `3rdparty/libpng`, and we need to keep all of them. But I can merge it to the one suppression and define all fun, like this:
```
{
   libpng
   Memcheck:Value8
   ...
   fun:png_do_read_transformations
   fun:png_read_image
   fun:png_read_row
}
```

2021-11-23 16:52 UTC, alalek commented
@asmorkalov Ping

2023-05-04 19:38 UTC, closed without merging