AudioIO: add dnn speech recognition sample on C++
opencv/opencv pull request #21458
Opened 2022-01-16 19:27 UTC by SinM9

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

2022-01-18 11:33 UTC, alalek commented on samples/dnn/speech_recognition.cpp
> +// You can download the converted onnx model from https://drive.google.com/drive/folders/1wLtxyao4ItAg8tt4Sb63zt6qXzhcQoR6?usp=sharing
It makes sense to move this information into command-line help output (e.g., line 511)

2022-01-18 11:33 UTC, alalek commented on samples/dnn/speech_recognition.cpp
> +        "{micro_time t       | 15                       | Duration of microphone work in seconds. Must be more than 6 sec }"
> micro_time

macro?
Please use "microphone" or "audio_duration".

---

> Duration of microphone work in seconds

"duration of audio chunk to be captured from microphone"

> Must be more than 6 sec

Could sample fill tail with zeros?

2022-01-18 11:33 UTC, alalek commented on samples/dnn/speech_recognition.cpp
> +        "{input_audio a      |                          | Path to input audio file        }"
> input_type
> input_audio

Please use one parameter:
> input_file

and `.has("input_file")` check (not specified - use microphone)

2022-01-18 11:33 UTC, alalek commented on samples/dnn/speech_recognition.cpp
> +        "{show_spectrogram s | off                      | Show a spectrogram of the input audio: on or off }"
> off

please reuse "bool" parameters of `CommandLineParser`. There is no ON/OFF.

2022-01-18 11:33 UTC, alalek commented on samples/dnn/speech_recognition.cpp
> +    }
> std::vector<std::vector<double>>& features

Please use `Mat` in `calculate_features()` instead and remove such manual "copy" conversion code (multiple places).

---

Use "copy-free" `.reshape()" to convert 2D into 3D tensor.

2022-01-18 11:33 UTC, alalek commented on samples/dnn/speech_recognition.cpp
> +    Mat featuresMat(sizes, CV_64F);
> CV_64F

DNN uses FP32 internally.

2022-01-18 11:33 UTC, alalek commented on samples/dnn/speech_recognition.cpp
> +    while ((sysTimeCurr - sysTimePrev) / cvTickFreq < microTime)
How do this check could guarantee that `inputAudio` contains enough samples and we don't lost something somewhere?

---

Check should be based on `inputAudio` content size and sample rate.

2022-01-18 11:33 UTC, alalek commented on samples/dnn/speech_recognition.cpp
> +    net.setPreferableTarget(parser.get<int>("target"));
To improve user experience it makes sense to load network before capturing audio (to avoid surprises after capturing from microphone).

2022-01-24 20:24 UTC, Qannaf requested changes

2022-01-24 20:24 UTC, Qannaf commented on samples/dnn/speech_recognition.cpp
> +    std::vector<std::vector<double>> mel(int n_mels, double fmin, double fmax)
```suggestion
    vector<vector<double>> mel(int n_mels, double fmin, double fmax)
```

2022-01-24 20:24 UTC, Qannaf commented on samples/dnn/speech_recognition.cpp
> +    std::vector<double> pad_window_center(std::vector<double>&data, int size)
```suggestion
    vector<double> pad_window_center(vector<double>&data, int size)
```

2022-01-24 20:24 UTC, Qannaf commented on samples/dnn/speech_recognition.cpp
> +        std::vector<double> pad_array;
```suggestion
        vector<double> pad_array;
```

2022-01-24 20:24 UTC, Qannaf commented on samples/dnn/speech_recognition.cpp
> +    std::vector<std::vector<double>> frame(std::vector<double>& x)
```suggestion
    vector<vector<double>> frame(vector<double>& x)
```

2022-01-24 20:24 UTC, Qannaf commented on samples/dnn/speech_recognition.cpp
> +        std::vector<std::vector<double>> new_x(n_fft, std::vector<double>(n_frames));
```suggestion
        vector<vector<double>> new_x(n_fft, vector<double>(n_frames));
```

2022-01-24 20:24 UTC, Qannaf commented on samples/dnn/speech_recognition.cpp
> +        std::vector<double> window_tensor;
```suggestion
        vector<double> window_tensor;
```

2022-01-24 20:24 UTC, Qannaf commented on samples/dnn/speech_recognition.cpp
> +    std::vector<std::vector<double>> stft_power(std::vector<double>& y)
```suggestion
    vector<vector<double>> stft_power(vector<double>& y)
```

2022-01-24 20:24 UTC, Qannaf commented on samples/dnn/speech_recognition.cpp
> +        std::vector<double> new_y;
```suggestion
        vector<double> new_y;
```

2022-02-22 19:20 UTC, alalek reviewed
Thank you for update!

2022-02-22 19:20 UTC, alalek commented on samples/dnn/speech_recognition.cpp
> +        "{show_spectrogram s | false                    | Show a spectrogram of the input audio: on or off }"
> on or off

true / false / 1 / 0

2022-02-22 19:20 UTC, alalek commented on samples/dnn/speech_recognition.cpp
> +    while ((sysTimeCurr - sysTimePrev) / cvTickFreq < microTime)
We should read until we fill buffer with enough data.
We don't need timeout check here as first capture may take some extra time for initialization and we will not have enough data in buffer for processing.

2022-02-28 13:31 UTC, alalek approved these changes
Well done :+1:

2022-02-28 15:23 UTC, merged