G-API: own::Mat::size
opencv/opencv pull request #21463
Opened 2022-01-17 09:36 UTC by mpashchenkov

The same MatSize structure for GAPI's own::Mat

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### Magic commands:
```
force_builders=Custom,Custom Win,Custom Mac
build_gapi_standalone:Linux x64=ade-0.1.1f
build_gapi_standalone:Win64=ade-0.1.1f
build_gapi_standalone:Mac=ade-0.1.1f
build_gapi_standalone:Linux x64 Debug=ade-0.1.1f

Xbuild_image:Custom=centos:7
Xbuildworker:Custom=linux-1
build_gapi_standalone:Custom=ade-0.1.1f

build_image:Custom=ubuntu-openvino-2021.4.1:20.04
build_image:Custom Win=openvino-2021.4.1
build_image:Custom Mac=openvino-2021.4.1

test_modules:Custom=gapi,python2,python3,java
test_modules:Custom Win=gapi,python2,python3,java
test_modules:Custom Mac=gapi,python2,python3,java

buildworker:Custom=linux-1
# disabled due high memory usage: test_opencl:Custom=ON
test_opencl:Custom=OFF
test_bigdata:Custom=1
test_filter:Custom=*
```

2022-01-21 09:15 UTC, mpashchenkov commented
@rgarnov, it is simple analogue of cv::MatSize for own::Mat.
I have questions:
- about place of MatSize, m b need to move to mat.hpp from types.hpp;
- Does it necessary add deownification for own::MatSize? I think, this struct is more for internal use;
- M B Need to add some specific possibilities for own::Mat or more tests.

Removed extra extensions for own::Size (not theme of this PR I think)

2022-01-21 09:38 UTC, dmatveev reviewed
👍 

@rgarnov awaiting for your review here

2022-01-21 09:39 UTC, dmatveev approved these changes

2022-02-08 08:18 UTC, rgarnov requested changes

2022-02-08 08:18 UTC, rgarnov commented on modules/gapi/include/opencv2/gapi/own/mat.hpp
> +                this->size = MatSize(&this->rows, &this->dims);
Looks like there is something incorrect with MatHeader/MatSize operator= if it doesn't work without this line

2022-02-08 08:44 UTC, rgarnov commented
> @rgarnov, it is simple analogue of cv::MatSize for own::Mat. I have questions:
> 
> * about place of MatSize, m b need to move to mat.hpp from types.hpp;
> * Does it necessary add deownification for own::MatSize? I think, this struct is more for internal use;
> * M B Need to add some specific possibilities for own::Mat or more tests.
> 
> Removed extra extensions for own::Size (not theme of this PR I think)

It's better to move MatSize to own/mat.hpp since it's used only there
There is no need for deownification of MatSize

2022-10-03 10:50 UTC, asmorkalov commented
@mpashchenkov @dmatveev Do you plan to finish the PR?

2022-10-03 11:26 UTC, mpashchenkov commented
@asmorkalov, I don't have time for this right now, I'll reopen it later.

2022-10-03 11:26 UTC, closed without merging

2022-10-04 00:46 UTC, dmatveev commented
That's sad, that was a good PR actually. @rgarnov would you mind taking this over? You've had comments to address.