ICP with scale
opencv/opencv pull request #21581
Opened 2022-02-08 19:26 UTC by DumDereDum

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ ] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

2022-02-10 08:54 UTC, alalek commented
> into `opencv:next`

wrong target branch

> do_not_target_to_shadow_branch

2022-04-29 12:06 UTC, savuor requested changes
Maybe I'll do these changes instead of @DumDereDum

2022-04-29 12:06 UTC, savuor commented on modules/3d/src/rgbd/odometry_functions.hpp
> +        C[6] = n1.dot(p1-p0);
This should be checked if this formula is to be fixed or not:
it's possible that there should be `n1.dot((p0 - currentTranslation)/currentScale)`, it's easier to do at caller's side.

2022-05-20 07:47 UTC, asmorkalov commented
@DumDereDum Friendly reminder.

2022-06-14 11:32 UTC, savuor commented
The algorithm does not converge even after a couple of fixes: the scale can drop to 0.02 or grow to 2.8 even when changing scale by 3%.
Since the code is not based on any known working solution, just on basic principles, it requires more deep research before making a PR.
But this would be easier to do in a different PR since it may require vast code changes.

2022-06-14 11:32 UTC, closed without merging