Add termination criteria to cv::fisheye::undistortPoints()
opencv/opencv pull request #21834
Opened 2022-04-07 15:57 UTC by victor1234

### Pull Request Readiness Checklist

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

#19138 

Wrap hardcoded termination criteria to `cv::TermCriteria` with default values from code

2022-04-08 05:17 UTC, asmorkalov requested changes

2022-04-08 05:17 UTC, asmorkalov commented on modules/calib3d/src/fisheye.cpp
> +        if (fabs(theta_d) > criteria.epsilon)
"Criteria type, can be one of: COUNT, EPS or COUNT + EPS": https://docs.opencv.org/4.x/d9/d5d/classcv_1_1TermCriteria.html#a56fecdc291ccaba8aad27d67ccf72c57
So need extra condition, if `criteria.epsilon` is valid value, but not random noise.

2022-04-08 05:17 UTC, asmorkalov commented on modules/calib3d/src/fisheye.cpp
> +            for (int j = 0; j < criteria.maxCount; j++)
The same here too.

2022-04-12 12:03 UTC, asmorkalov approved these changes
:+1:

2022-04-12 12:03 UTC, asmorkalov commented
/cc @vpisarev Please lay attention on API change.

2022-04-15 07:09 UTC, vpisarev approved these changes

2022-04-16 17:59 UTC, merged