select correct MediaType in MSMF backend.
opencv/opencv pull request #22347
Opened 2022-08-06 08:09 UTC by bu3w

There may be more than one streams in some camera device (for example RealSense D405)
some streaming setting may be not regular visualable image.
But, in MSMF backend, by default, regular visualable image is require.

This patch will skip some streaming base on the format.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

2022-08-15 09:06 UTC, zihaomu approved these changes
Thanks for your contribution! 👍 
I have tested this PR with Orbbec camera (Astra +) and it works fine both on the Depth stream and RGB stream.

2022-08-19 08:41 UTC, alalek requested changes

2022-08-19 08:41 UTC, alalek commented on modules/videoio/src/cap_msmf.cpp
>          }
> 100644 → 100755

Revert attribute change

2022-08-25 04:18 UTC, bu3w commented on modules/videoio/src/cap_msmf.cpp
>          }
Thanks. fixed.

2022-08-25 10:46 UTC, alalek approved these changes

2022-08-26 09:49 UTC, merged