Tutorial for Generalized Hough Ballard and Guil Transform
opencv/opencv pull request #22482
Opened 2022-09-08 01:43 UTC by Glutamat42

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x ] I agree to contribute to the project under Apache 2 License.
- [x ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x ] The PR is proposed to the proper branch (i hope so)
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x ] The feature is well documented and sample code can be built with the project CMake

2022-09-08 06:20 UTC, asmorkalov requested changes

2022-09-08 06:20 UTC, asmorkalov commented on doc/tutorials/objdetect/generalized_hough_ballard_guil/generalized_hough_ballard_guil.markdown
> +Mat image = imread("images/generalized_hough_mini_image.jpg");
The  common OpenCV approach is not to hard-code examples in markdown, but include code snippets with doxygen notation. Code snippets in form of C++ files are check with compiler.
Multi-language example:
- tutorial https://raw.githubusercontent.com/opencv/opencv/4.x/doc/tutorials/core/basic_linear_transform/basic_linear_transform.markdown
- https://github.com/opencv/opencv/blob/4.x/samples/cpp/tutorial_code/ImgProc/BasicLinearTransforms.cpp

In your case you need only `@snippet` directive without language switch.

2022-09-09 13:45 UTC, sturkmen72 commented
in my opinion the tutorial should go here https://docs.opencv.org/4.x/d7/da8/tutorial_table_of_content_imgproc.html
and sample code should go https://github.com/opencv/opencv/tree/4.x/samples/cpp/tutorial_code/ImgTrans

2022-09-12 07:44 UTC, asmorkalov approved these changes
:+1: Thanks a lot for the contribution!

2022-09-12 07:45 UTC, merged