Fix #22767: Ensure that the buttons are spaced to the size of the toolbar window, which is always visible.
opencv/opencv pull request #22806
Opened 2022-11-15 00:27 UTC by dan-masek

This fixes some of the problems -- when toolbars are created in one go, and some go outside the window bounds (when main client are becomes nothing), they will get sized correctly.

However, with `WINDOW_NORMAL`, some wonkiness still remains and blank buttons tend to appear once in a while (this might be due to the spacers).

Ideally, the trackbars should automatically resize to fit the width of the main window, when said window is resized (either manually when in `NORMAL` mode, or by code). This might however break some existing code that relies on current behaviour to place multiple trackbars on single row. Any opinions?

2022-11-17 15:16 UTC, AleksandrPanov requested changes
Checked, the problem is reproduced, PR fixes the problem. Issue affects to 3.4, need to make a fix in 3.4

before fix:
![1](https://user-images.githubusercontent.com/22337800/202484810-9c228746-44fe-4de4-bea9-e2adff1dbc9a.PNG)

after fix:
![2](https://user-images.githubusercontent.com/22337800/202484815-dd79ed10-b7f3-4856-9d6a-41d363bd6310.PNG)

2022-11-17 15:19 UTC, alalek commented
This patch should go into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first.
We will merge changes from 3.4 into 4.x regularly (weekly/bi-weekly).

Please:
- change "base" branch of this PR: 4.x => 3.4 (use "Edit" button near PR title)
- rebase your commits from 4.x onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/4.x`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".

2022-11-17 15:39 UTC, dan-masek commented
Sounds good. I'm on the road for couple more days, I'll have a look at it over the weekend.

2022-11-21 19:27 UTC, alalek approved these changes
Thank you :+1:

2022-11-21 19:53 UTC, merged