Fix encodeStructuredAppend() resulting in only one QR code problem
opencv/opencv pull request #23104
Opened 2023-01-07 11:32 UTC by genciberisha

Related issue: [#22205](https://github.com/opencv/opencv/issues/22205)

While splitting the data to multiple QR codes  it constantly cleans the resulting vector(final_qr_codes).
The fix is to just clean the result vector after all work is done with it.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

2023-01-07 12:15 UTC, genciberisha commented
@alalek Can you please check ?

2023-01-08 01:13 UTC, alalek commented
Thank you for the contribution!

Please add a regression test case for this:
- test case should fail without this patch
- test case should pass with this fix.

2023-01-15 03:03 UTC, genciberisha commented
@AleksandrPanov Can you please review this ?

2023-01-16 00:24 UTC, AleksandrPanov requested changes
Also please squash the commits into one.

2023-01-16 00:24 UTC, AleksandrPanov commented on modules/objdetect/test/test_qrcode_encode.cpp
> +TEST(Objdetect_QRCode_Encode_Decode_Structured_Append, regression)
Add the number of the issue that is being fixed:
TEST(Objdetect_QRCode_Encode_Decode_Structured_Append, regression_22205)

2023-01-16 00:24 UTC, AleksandrPanov commented on modules/objdetect/test/test_qrcode_encode.cpp
> +                                                            "to the one returned";
Add validation of the QR code content.

2023-01-22 00:16 UTC, closed without merging

2023-01-22 01:12 UTC, genciberisha commented
This PR is closed for various reasons, if you want to follow up to this go [here](https://github.com/opencv/opencv/pull/23168).