add charuco pattern into calibration.cpp
opencv/opencv pull request #23486
Opened 2023-04-12 20:52 UTC by vovka643

added charuco pattern into calibration.cpp. Added charuco pattern with predefined aruco dictionary and with dictionary from file.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [х] I agree to contribute to the project under Apache 2 License.
- [х] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [х] The PR is proposed to the proper branch
- [х] There is a reference to the original bug report and related work
- [х] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [х] The feature is well documented and sample code can be built with the project CMake

2023-04-13 06:29 UTC, asmorkalov requested changes

2023-04-13 06:29 UTC, asmorkalov commented on samples/cpp/calibration.cpp
> +        "     [-ad=<arucoDict>]        # number of predefined aruco dictionary"
"Aruco dictionary name for charuco board"

2023-04-13 06:29 UTC, asmorkalov commented on samples/cpp/calibration.cpp
> +        "     [-adf=<dictFilename>]   # filename of aruco dictionary"
"Custom aruco dictionary file for charuco board"

2023-04-13 06:29 UTC, asmorkalov commented on samples/cpp/calibration.cpp
> +                    cv::makePtr<cv::aruco::CharucoBoard>(cv::aruco::CharucoBoard({ boardSize.width + 1,boardSize.height + 1 },
No need to use `cv::Ptr` for board. You can allocate it on stack as local variable.

2023-04-13 06:29 UTC, asmorkalov commented on samples/cpp/calibration.cpp
> +                }
No need to create yet another detector. CharucoBoard has `detectBoard` method. It does all you need.

2023-04-13 06:30 UTC, asmorkalov requested changes

2023-04-14 16:58 UTC, asmorkalov commented on samples/cpp/calibration.cpp
> +                cv::aruco::CharucoBoard ch_board ({ boardSize.width + 1, boardSize.height + 1 },
Why +1?

2023-04-14 16:58 UTC, asmorkalov commented on samples/cpp/calibration.cpp
> +                cv::aruco::ArucoDetector aruco_detector(dictionary);
ArucoDetector is not used.

2023-04-14 16:58 UTC, asmorkalov commented on samples/cpp/calibration.cpp
> +                    found = false;
You can initialize found as false beforehand and get rid of all else branches.

2023-04-17 07:39 UTC, asmorkalov commented on samples/cpp/calibration.cpp
> +                cv::aruco::CharucoBoard ch_board ({ boardSize.width + 1, boardSize.height + 1 },
Still relevant.

2023-04-18 06:28 UTC, asmorkalov commented
```
/home/ci/opencv/samples/cpp/calibration.cpp:552:122: warning: enum constant in boolean context [-Wint-in-bool-context]

/home/ci/opencv/samples/cpp/calibration.cpp:565:37: warning: comparison of integer expressions of different signedness: 'std::vector<cv::Point_<float> >::size_type' {aka 'long unsigned int'} and 'int' [-Wsign-compare]
```

2023-04-18 12:30 UTC, asmorkalov commented
```
./example_cpp_calibration -w=7 -h=5 -pt=charucoboard -ad=DICT_5X5_100 ./calib.list -o=charuco_calib.yaml
...
ERRORS:
Parameter 'ad': can not convert: [DICT_5X5_100] to [int]
```

2023-04-18 12:30 UTC, asmorkalov requested changes

2023-04-18 13:12 UTC, asmorkalov commented
The sample uses wrong visualization or something is broken in the pipeline. I see this:
![preview_1](https://user-images.githubusercontent.com/2536374/232788305-4dcadaf7-eab3-437d-85be-0b7015a2477d.jpg)

2023-04-18 14:06 UTC, vovka643 commented
You should write inner corners of desk.  For your desk you should use parameters: h=4, w =6

2023-04-19 13:03 UTC, asmorkalov requested changes

2023-04-19 13:04 UTC, asmorkalov commented
Please ignore my previous statement about wrong visualization and calibration. I screwed up with board size. `./example_cpp_calibration -w=4 -h=6 -pt=chessboard ./calib.list -o=charuco_calib.yaml` works expected.

2023-04-21 06:35 UTC, asmorkalov commented on samples/cpp/calibration.cpp
> +    cv::aruco::CharucoBoard ch_board({ boardSize.width + 1, boardSize.height + 1 },
Why +1?

2023-04-21 06:37 UTC, asmorkalov commented on samples/cpp/calibration.cpp
> +                if (pointbuf.size() < (long int) (boardSize.height*boardSize.width)) {
I propose to cast to size_t.

2023-04-24 09:17 UTC, asmorkalov commented on samples/cpp/calibration.cpp
> +    cv::aruco::CharucoBoard ch_board({ boardSize.width + 1, boardSize.height + 1 },
Discussed the issue offline. Decided to remove +1, but add note about the board size units. Chessboard and radon board size are defined in inner corners, all other boards - in elements (circles or squares).

2023-04-24 09:18 UTC, asmorkalov commented on samples/cpp/calibration.cpp
> +                cv::aruco::CharucoBoard ch_board ({ boardSize.width + 1, boardSize.height + 1 },
Discussed the issue offline. Decided to remove +1, but add note about the board size units. Chessboard and radon board size are defined in inner corners, all other boards - in elements (circles or squares).

2023-04-24 09:18 UTC, asmorkalov commented on samples/cpp/calibration.cpp
> +        "DICT_APRILTAG_16h5, DICT_APRILTAG_25h9, DICT_APRILTAG_36h10, "
No space at the end of the line.

2023-04-26 08:01 UTC, asmorkalov approved these changes
:+1: Tested manually with command `./example_cpp_calibration -w=5 -h=7 -pt=charuco -ad=DICT_5X5_100 ./calib.xml -o=charuco_calib.yml` and template from https://github.com/opencv/opencv/pull/23363/

2023-04-26 09:13 UTC, merged