Error with an incorrect trained Haar model
opencv/opencv pull request #23498
Opened 2023-04-16 02:55 UTC by georgedem975

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a [reference](https://github.com/opencv/opencv/issues/23497) to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

2023-04-16 02:57 UTC, georgedem975 commented
so far, I have found such a flaw in only one model, but if necessary, I can view all the other models and check them for performance

2023-04-17 06:16 UTC, asmorkalov commented
@georgedem975 Could you provide details on the issue? Please submit a ticket with image and sample code or command line to use existing sample to reproduce the issue.

2023-04-18 18:28 UTC, opencv-alalek requested changes
I believe this file should be dropped completely (at least for 5.x):
- the file is not tested and not used in OpenCV (however some demo videos are available on YT: e.g, https://www.youtube.com/watch?v=7x1jowSCWNY )
- perhaps file has licensing issues for commercial usage
- provided links on related resources are dead
- this approach is useful for learning/education purpose only. Nowadays DNN-based solutions provides much better accuracy (see "pedestrian detection" task, e.g. from ADAS algorithms)

2023-04-18 18:28 UTC, opencv-alalek commented on data/haarcascades_cuda/haarcascade_fullbody.xml
> +  <size>28 14</size>
> `14x28 fullbody detector`

That change contradicts the description.

Bodies are usually vertically aligned, so `height > width`

2023-09-20 12:46 UTC, closed without merging