Vectorize cv::resize for INTER_AREA
opencv/opencv pull request #23525
Opened 2023-04-21 22:24 UTC by vrabaud

This is just a vectorization of the original code. I'll make speed tests once this PR is reviewed.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

2023-04-22 05:50 UTC, asmorkalov commented
QR code decoding pipeline uses resize INTER_AREA internally. The python test crash may be caused by the optimization.

2023-04-27 11:07 UTC, vrabaud commented
@asmorkalov , I am trying to get accurate perf results with "modules/ts/misc/run.py" following https://github.com/opencv/opencv/wiki/HowToUsePerfTests. What options can I use to get more accurate results ? Like ```--perf_force_samples```. 

@vpisarev , to speed-up saturate_cast over several samples, I had to implement a HAL version. Is there any way to make https://github.com/opencv/opencv/blob/af1c63c0a027f1d9e3e7720b66cee7e4161e186d/modules/core/src/precomp.hpp#L237 usable by other modules ? Or is the recommended way to wrap the data in a cv::Mat and call convertTo even though there is some overhead to both operations ?

2023-05-23 10:23 UTC, asmorkalov commented
Hello @vrabaud I made some research of your patch and result is very controversial. For my AMD Ryzen7 2700X it does not improve performance at all. The difference is comparable with statistics fluctuations. For Jetson NANO (arm v8 x64 by NVIDIA) I see performance speedup for small images. Looks like the speedup is related to more efficient cache reuse. HD images and larger with 3-4 channels become slower. For Jetson tk1 (armv7) I see the same behavior, but size threshold is even lower than for Jetson NANO. Most of resolutions have degradation.

I attached archive with all experiments (xml).
[resize_perf.zip](https://github.com/opencv/opencv/files/11542544/resize_perf.zip)

2023-05-23 10:23 UTC, asmorkalov requested changes
The PR does not demonstrate stable performance improvement.

2023-05-23 14:05 UTC, vrabaud commented
Thx for checking. Let me try two things:
- a load/store using a step for the second pass so that we do not do two transpositions
- a vectorization of the multiplication but not the summation. That should beat the loop unrolling at least.

2023-09-20 12:30 UTC, asmorkalov commented
@vrabaud do you plan to work on it or I may close the PR?

2023-09-21 22:44 UTC, opencv-alalek commented
@vrabaud BTW, there is `Draft` feature for PRs:

`Still in progress? Convert to draft` under "Reviewers" section

2023-10-20 11:23 UTC, asmorkalov commented
@vrabaud Should I close this after https://github.com/opencv/opencv/pull/24412 merge?

2023-10-20 12:10 UTC, vrabaud commented
Actually no: the other PR is just about line merging. I will now specialize this one for column merging. Almost done :)

2025-03-14 06:20 UTC, asmorkalov commented
@vrabaud Is the PR still relevant?

2025-03-20 09:10 UTC, vrabaud commented
https://github.com/opencv/opencv/pull/24412 actually got most of the speed-up. Doing the transpose here is too slow. A last solution is to first pack the image vertically, then process the columns  in parallel. But the load/store are slow as the memory is not contiguous, for operations that are already partially parallel for 2,3,4 channels. parts of the registers are not used in those cases but that does not bring any measurable speed-up.
Stopping here.

2025-03-20 09:10 UTC, closed without merging