Dnn_ Net_ A bug occurred when compiling getUnconnectedOutLayersNames into JavaScript
opencv/opencv pull request #24458
Opened 2023-10-26 13:35 UTC by laolaolulu

ret_type = re.sub('(^|[^\w])' + key + '($|[^\w])', type_dict[key], ret_type)
When compiling JavaScript, this code converts vector<std:: string>to vector std:: string
Details: https://laolaolulu.github.io/posts/emscripten-opencv/#opencvjs%E7%BC%96%E8%AF%91getunconnectedoutlayersnames%E8%BF%87%E7%A8%8B%E4%B8%AD%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86

2023-10-26 14:44 UTC, asmorkalov commented
```
Run cd $HOME/build
Scanning dependencies of target check_flake8
Running flake8
./modules/js/generator/embindgen.py:485:69: E999 TabError: inconsistent use of tabs and spaces in indentation
	    ret_type = re.sub(r"\b" + key + r"\b", type_dict[key], ret_type)
                                                                    ^
1     E999 TabError: inconsistent use of tabs and spaces in indentation
1
make[3]: *** [CMakeFiles/check_flake8.dir/build.make:58: CMakeFiles/check_flake8] Error 1
```

2023-10-26 17:16 UTC, asmorkalov commented
```
modules/js/src/core_bindings.cpp:463: trailing whitespace.
+    register_vector<double>("DoubleVector"); 
```

2023-10-27 04:40 UTC, asmorkalov commented
@laolaolulu please revert formatting changes. Pure code re-formatting does not bring value, but makes review harder, merge conflicts in 4.x->5.x merges and other issues for maintainers.

2023-10-28 08:39 UTC, laolaolulu commented
> @laolaolulu please revert formatting changes. Pure code re-formatting does not bring value, but makes review harder, merge conflicts in 4.x->5.x merges and other issues for maintainers.

What formatting code plugin should I use for the vscode I am using?

2023-10-30 09:30 UTC, asmorkalov commented
Wiki page on coding style and formatting: https://github.com/opencv/opencv/wiki/Coding_Style_Guide
We recommend you the codding style above and .clang-format attached to the wiki page, but for new code only. Please do not touch not relevant pieces.

2023-11-09 17:27 UTC, asmorkalov commented on platforms/js/build_js.py
> +
The new parameters are not used in the script.

2023-11-09 17:39 UTC, asmorkalov requested changes
Changes in opencv_js.config.py are missing.

2023-11-13 11:49 UTC, asmorkalov approved these changes
:+1:

2023-11-13 11:51 UTC, merged