Update checkchessboard.cpp
opencv/opencv pull request #24558
Opened 2023-11-19 14:17 UTC by thewoz

This pull request resolves issue #23558.

In the issue #23558 an empty image was passed to the findChessboardCorners() function with the CALIB_CB_FAST_CHECK flag. The fast check failed and findChessboardCorners() wasted 15minutes finding a checkerboard that was not there in the image.

The reason is that the checkChessboardBinary() function returned true because the checkQuads() function was convinced that among all the contours found by fillQuads() were those of the checkerboard.

The problem was icvGetQuadrangleHypotheses() that incorrectly filtering the contours found. It was passing too many contours to checkQuads(), and by the law of large numbers, checkQuads() was able to find contours that "looked" like a checkerboard between them.

What I did is to shrink the parameters in the icvGetQuadrangleHypotheses() function. I changed the range of the ratio between the sides of the contour found to 0.5 and 1.5. More reasonable values than the previous 0.3 and 3.0 In addition, I raised the minimum side length of the hypothetical square from 10 to 25 pixels.

After the change I tried the function on other checkerboard images and had no problems

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [X] I agree to contribute to the project under Apache 2 License.
- [X] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [X] The PR is proposed to the proper branch
- [X] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

2023-11-20 09:13 UTC, asmorkalov commented
@thewoz Thanks a lot for the contribution. The PR introduces existing test regression:
```
[ RUN      ] Calib3d_ChessboardDetector.timing
C:\build\precommit_windows64\4.x\opencv\modules\ts\src\ts.cpp(618): error: Failed

	failure reason: Invalid function output
	test case #-1
	seed: 00000000000c5a7c
-----------------------------------
	LOG:
chess3.png: chessboard 1:
Error: chessboard was not detected in the image chess3.png

-----------------------------------

[  FAILED  ] Calib3d_ChessboardDetector.timing (7 ms)
```

2023-11-20 15:17 UTC, thewoz commented
sorry where I can found the chess3.png images?

2023-11-20 19:41 UTC, s-trinh commented
@thewoz 
It should be this image: https://github.com/opencv/opencv_extra/blob/38d14db05e43edd9f44e673cfd296ff67a210222/testdata/cv/cameracalibration/chess3.png

2023-11-20 22:06 UTC, thewoz commented
Hi,
I have test the pull request against the images:
BoardStereoL1-6.png BoardStereoR1-6.png and chess1-6.png 

in 

https://github.com/opencv/opencv_extra/tree/4.x/testdata/cv/cameracalibration

and the chessboard was found in each of them.
so is not clear to me the failed in the test

2023-11-21 06:47 UTC, vpisarev commented
@thewoz, basically, you should clone opencv_extra repository and then set OPENCV_TEST_DATA_PATH environment variable pointing to <opencv_extra_dir>/testdata.

2023-11-21 16:05 UTC, thewoz commented
Hi,
I should have fixed the problem on the image chess3.png

2023-11-22 08:55 UTC, AleksandrPanov commented
```
[ RUN      ] Calib3d_ChessboardDetector.timing
/home/ci/opencv/modules/ts/src/ts.cpp:618: Failure
Failed

	failure reason: Invalid function output
	test case #4
	seed: 00000000000c5a60
-----------------------------------
	LOG:
chess3.png: chessboard 1:
    cvCheckChessboard time s: 0.000000, us per pixel: 0.000000
    cvFindChessboard time s: 0.000000, us per pixel: 0.000000
chess1.png: chessboard 1:
    cvCheckChessboard time s: 0.000000, us per pixel: 0.000000
    cvFindChessboard time s: 0.000000, us per pixel: 0.000000
../shared/baboon.png: chessboard 0:
    cvCheckChessboard time s: 0.000000, us per pixel: 0.000000
    cvFindChessboard time s: 0.000000, us per pixel: 0.000000
../shared/box_in_scene.png: chessboard 0:
    cvCheckChessboard time s: 0.000000, us per pixel: 0.000000
    cvFindChessboard time s: 0.000000, us per pixel: 0.000000
../shared/airplane.png: chessboard 0:
    cvCheckChessboard time s: 0.000000, us per pixel: 0.000000
    cvFindChessboard time s: 0.000000, us per pixel: 0.000000
chessboard-artificial2.png: chessboard 1:
Error: chessboard was not detected in the image chessboard-artificial2.png

-----------------------------------
	CONSOLE: ...
-----------------------------------

[  FAILED  ] Calib3d_ChessboardDetector.timing (164 ms)
```

2023-11-23 15:42 UTC, thewoz commented
Hello everyone,
everyone seems to be working now.
All tests are passed

2023-11-24 13:14 UTC, thewoz commented
sorry I forgot to erase a include file that I use for the debug

2023-12-01 10:46 UTC, thewoz commented
Hello everyone is there anything else I can do ?

2023-12-01 11:46 UTC, asmorkalov commented
@vpisarev could you take a look too?

2023-12-14 08:37 UTC, thewoz commented
is there anything i can do?

2023-12-19 07:54 UTC, vpisarev approved these changes

2023-12-19 07:54 UTC, vpisarev commented
@thewoz, thank you! I think, the patch can be merged.

2023-12-19 19:57 UTC, AleksandrPanov requested changes
1. need to fix extra `\n`
2. what is the performance? reabase to https://github.com/opencv/opencv/pull/24605#event-11212616852, this PR improves performance.
3. I suggest to use `approxPolyDP()` instead `box_area_covered`

2023-12-19 19:57 UTC, AleksandrPanov commented on modules/calib3d/src/checkchessboard.cpp
> +
extra `\n`

2023-12-19 19:57 UTC, AleksandrPanov commented on modules/calib3d/src/checkchessboard.cpp
> +
extra `\n`

2023-12-19 19:57 UTC, AleksandrPanov commented on modules/calib3d/src/checkchessboard.cpp
> +
extra `\n`

2023-12-20 15:31 UTC, thewoz commented on modules/calib3d/src/checkchessboard.cpp
> +
Hi @AleksandrPanov I never perform a rebase.
Can you help me? Sorry about that...

2023-12-22 07:02 UTC, AleksandrPanov commented on modules/calib3d/src/checkchessboard.cpp
> +
checkout your branch to 4.x, update your 4.x branch from https://github.com/opencv/opencv, checkout your branch to [fix-issue-23558](https://github.com/thewoz/opencv/tree/fix-issue-23558), rebase and resolve conflicts:
```
git checkout 4.x
git pull https://github.com/opencv/opencv
git checkout fix-issue-23558
git rebase 4.x
git push -f
```

2024-01-09 09:49 UTC, thewoz commented
Hello everyone,
I was trying the modification suggested by @AleksandrPanov to try to use the approxPolyDP() function and it wasn't working too well.
Anyway doing some testing I realized that today's version of 4.x no longer gives the issue #23558 
I think that the pull [fix-issue-23558](https://github.com/thewoz/opencv/tree/fix-issue-23558), has solved this #23558 
At this point I would say that this pull of mine is useless.

2024-01-09 09:49 UTC, closed without merging

2024-01-10 12:11 UTC, AleksandrPanov commented
@thewoz, I tried to use the approxPolyDP() func too, and it really wasn't working too well. You could try to call this function twice, but it doesn't look like a good solution.

Now I think that use `minAreaRect` and `box_area_covered` is better. Thanks for the good idea.

2024-01-10 22:16 UTC, thewoz commented
Hi @AleksandrPanov... yes, we could try to run approxPolyDP() twice (I haven't tried yet). 
However, my concern is that approxPolyDP() is a bit too sensitive to the sharpeness of the edges of the checkerboard squares.
My idea is that using `minAreaRect` and `box_area_covered` would make the process a little less sensitive to this problematic.
Anyway, the reason I tried to implement this solution is to solve problem https://github.com/opencv/opencv/issues/23558, in which too many contours were found in an image and `checkChessboardBinary()` thought there was a checkerboard. 
So I wanted to try to implement a method that would remove those contours that could not be considered square. 
Up to now the pull request #24605 seems to have solved the problem https://github.com/opencv/opencv/issues/23558

2024-01-15 10:23 UTC, AleksandrPanov commented
@thewoz, there are not enough tests in OpenCV for findchessboardcorners() and therefore algorithm changes can cause regressions that we may not catch.
We merged PR #24605 because it just adds optimizations without changing the algorithm.

We want to expand the test suite, but this is a big task. After that, we will try to improve the code based on your ideas.

2024-01-15 12:17 UTC, thewoz commented
Hi @AleksandrPanov,
I completely understand what you mean and I fully agree with you.
Thank you for all the work