Merge 4.x -> 5.x
opencv/opencv pull request #25745
Opened 2024-06-11 17:12 UTC by mshabunin

My attempt to make regular merge :slightly_smiling_face: 

Note: there is a conflict between #25524 and #25458

2024-06-12 12:47 UTC, vrabaud commented
@mshabunin , it seems you are not including all of https://github.com/opencv/opencv/pull/25665 Only missing: `Jptr += 18;` line 405 in 3d/src/fundam.cpp

2024-06-12 12:57 UTC, mshabunin commented
Yes, thank you! I added this change and test works better now. Though one case is still failing (LMEDS):
```
[ RUN      ] Calib3d_Homography.Refine
/work/opencv/modules/3d/test/test_homography.cpp:763: Failure
Expected: (sqrt(error.at<double>(0, 0))) <= (method == LMEDS ? 7e-4 : 7e-5), actual: 0.0041369 vs 0.0007
[  FAILED  ] Calib3d_Homography.Refine (2 ms)
```

2024-06-12 13:15 UTC, vrabaud commented
That test was added to exercise the Jacobian usage. Indeed, if the LM solver is different, that does not help. Maybe you can try increasing the number of iterations from 10 to 20 to see if that improves the error ?

2024-06-12 15:30 UTC, dkurt commented
@vrabaud, seems like it always 10: https://github.com/opencv/opencv/blob/a2d2ea6536df143ca118abc0fbe095e7dadbebd2/modules/3d/src/fundam.cpp#L408

@mshabunin, I think it’s ok to increase threshold for 5.x. As we see, with Jacobian fix the error decreased from 0.0100815 to 0.0041369. The test is quite synthetic and catches Jacobian patch only.

2024-06-12 20:08 UTC, mshabunin commented
Thank you! I tried to increase number of iterations, but it did not help. So I've updated the test threshold.

2024-06-14 07:46 UTC, mshabunin commented
@alexlyulkov , please take a look at the dnn part of this PR - whether I've correctly merged parts with OpenVINO support (there were discrepancies between #25524 and #25458).

2024-06-25 13:38 UTC, asmorkalov commented
minmax.dispatch.cpp changes are missing:
```diff
diff --git a/modules/core/src/minmax.dispatch.cpp b/modules/core/src/minmax.dispatch.cpp
index cd778b0283..6c50cb20b5 100644
--- a/modules/core/src/minmax.dispatch.cpp
+++ b/modules/core/src/minmax.dispatch.cpp
@@ -309,33 +309,6 @@ void cv::minMaxIdx(InputArray _src, double* minVal,
                ocl_minMaxIdx(_src, minVal, maxVal, minIdx, maxIdx, _mask))
 
     Mat src = _src.getMat(), mask = _mask.getMat();
-
-    if (src.dims <= 2)
-    {
-        CALL_HAL(minMaxIdx, cv_hal_minMaxIdx, src.data, src.step, src.cols*cn, src.rows,
-                 src.depth(), minVal, maxVal, minIdx, maxIdx, mask.data);
-    }
-    else if (src.isContinuous())
-    {
-        int res = cv_hal_minMaxIdx(src.data, 0, (int)src.total()*cn, 1, src.depth(),
-                                   minVal, maxVal, minIdx, maxIdx, mask.data);
-
-        if (res == CV_HAL_ERROR_OK)
-        {
-            // minIdx[0] and minIdx[0] are always 0 for "flatten" version
-            if (minIdx)
-                ofs2idx(src, minIdx[1], minIdx);
-            if (maxIdx)
-                ofs2idx(src, maxIdx[1], maxIdx);
-            return;
-        }
-        else if (res != CV_HAL_ERROR_NOT_IMPLEMENTED)
-        {
-            CV_Error_(cv::Error::StsInternal,
-            ("HAL implementation minMaxIdx ==> " CVAUX_STR(cv_hal_minMaxIdx) " returned %d (0x%08x)", res, res));
-        }
-    }
-
     MinMaxIdxFunc func = getMinMaxIdxFunc(depth);
     CV_Assert( func != 0 );
```

2024-06-25 14:13 UTC, asmorkalov requested changes

2024-06-25 14:13 UTC, asmorkalov commented on modules/3d/src/hal_replacement.hpp
> +inline int hal_ni_project_points_pinhole64f(const double* src_data, size_t src_step, size_t src_size,
The integration part of HAL is missing in the PR. `undistortPoints` was reworked in 5.x. I'll attach solution soon.

2024-06-25 19:20 UTC, mshabunin commented on modules/dnn/src/layers/gather_elements_layer.cpp
>          auto gatherElements = std::make_shared<ov::op::v6::GatherElements>(
Restored 5.x version

2024-06-25 19:20 UTC, mshabunin commented on modules/dnn/src/layers/gather_layer.cpp
> -            nodes[1].dynamicCast<InfEngineNgraphNode>()->node,
Restored 5.x version

2024-06-25 19:20 UTC, mshabunin commented on modules/dnn/src/layers/scatterND_layer.cpp
> -            nodes[1].dynamicCast<InfEngineNgraphNode>()->node,
Restored 5.x version

2024-06-25 19:20 UTC, mshabunin commented on modules/dnn/src/layers/scatter_layer.cpp
>              indicesBound);
Restored 5.x version

2024-06-25 19:20 UTC, mshabunin commented on modules/imgproc/test/test_contours_new.cpp
> +        // See https://github.com/opencv/opencv/issues/25663 for details.
Removed this message

2024-06-25 19:22 UTC, mshabunin commented
I've copied that code block to minmax.dispatch.cpp. Perhaps we need to partially backport minmax changes to 4.x to avoid issues in future (is it #24962?).

2024-06-26 07:38 UTC, asmorkalov commented
@mshabunin The patch for the `projectPoints` HAL:
```
diff --git a/modules/3d/src/calibration_base.cpp b/modules/3d/src/calibration_base.cpp
index e087111efb..e3886375cd 100644
--- a/modules/3d/src/calibration_base.cpp
+++ b/modules/3d/src/calibration_base.cpp
@@ -41,6 +41,7 @@
 //M*/
 
 #include "precomp.hpp"
+#include "hal_replacement.hpp"
 #include "distortion_model.hpp"
 #include <stdio.h>
 #include <iterator>
@@ -539,20 +540,15 @@ void cv::projectPoints( InputArray _objectPoints,
               (objectPoints.rows == count && objpt_cn*objectPoints.cols == 3) ||
               (objectPoints.rows == 3 && objpt_cn == 1 && objectPoints.cols == count));
 
-    Mat matM(objectPoints.size(), CV_64FC(objpt_cn));
-    objectPoints.convertTo(matM, CV_64F);
     if (objectPoints.rows == 3 && objectPoints.cols == count) {
         Mat temp;
-        transpose(matM, temp);
-        matM = temp;
+        transpose(objectPoints, temp);
+        objectPoints = temp;
     }
 
     CV_Assert( _imagePoints.needed() );
     _imagePoints.create(count, 1, CV_MAKETYPE(objpt_depth, 2), -1, true);
     Mat ipoints = _imagePoints.getMat();
-    ipoints.convertTo(_m, CV_64F);
-    const Point3d* M = matM.ptr<Point3d>();
-    Point2d* m = _m.ptr<Point2d>();
 
     Mat rvec = _rvec.getMat(), tvec = _tvec.getMat();
     if(!((rvec.depth() == CV_32F || rvec.depth() == CV_64F) &&
@@ -656,6 +652,127 @@ void cv::projectPoints( InputArray _objectPoints,
     bool calc_derivatives = dpdr.data || dpdt.data || dpdf.data ||
                             dpdc.data || dpdk.data || dpdo.data;
 
+    if (!calc_derivatives)
+    {
+        if (objpt_depth == CV_32F && ipoints.type() == CV_32F)
+        {
+            float rtMatrix[12] = { (float)R[0], (float)R[1], (float)R[2], (float)t[0],
+                                (float)R[3], (float)R[4], (float)R[5], (float)t[1],
+                                (float)R[6], (float)R[7], (float)R[8], (float)t[2] };
+
+            cv_camera_intrinsics_pinhole_32f intr;
+            intr.fx = (float)fx; intr.fy = (float)fy;
+            intr.cx = (float)cx; intr.cy = (float)cy;
+            intr.amt_k = 0; intr.amt_p = 0; intr.amt_s = 0; intr.use_tau = false;
+
+            switch (ktotal)
+            {
+            case  0: break;
+            case  4: // [k_1, k_2, p_1, p_2]
+                intr.amt_k = 2; intr.amt_p = 2;
+                break;
+            case  5: // [k_1, k_2, p_1, p_2, k_3]
+                intr.amt_k = 3; intr.amt_p = 2;
+                break;
+            case  8: // [k_1, k_2, p_1, p_2, k_3, k_4, k_5, k_6]
+                intr.amt_k = 6; intr.amt_p = 2;
+                break;
+            case 12: // [k_1, k_2, p_1, p_2, k_3, k_4, k_5, k_6, s_1, s_2, s_3, s_4]
+                intr.amt_k = 6; intr.amt_p = 2; intr.amt_s = 4;
+                break;
+            case 14: // [k_1, k_2, p_1, p_2, k_3, k_4, k_5, k_6, s_1, s_2, s_3, s_4, tau_x, tau_y]
+                intr.amt_k = 6; intr.amt_p = 2; intr.amt_s = 4; intr.use_tau = true;
+                break;
+            default:
+                CV_Error(cv::Error::StsInternal, "Wrong number of distortion coefficients");
+            }
+
+            intr.k[0] = (float)k[0];
+            intr.k[1] = (float)k[1];
+            intr.k[2] = (float)k[4];
+            intr.k[3] = (float)k[5];
+            intr.k[4] = (float)k[6];
+            intr.k[5] = (float)k[7];
+
+            intr.p[0] = (float)k[2];
+            intr.p[1] = (float)k[3];
+
+            for (int ctr = 0; ctr < 4; ctr++)
+            {
+                intr.s[ctr] = (float)k[8+ctr];
+            }
+
+            intr.tau_x = (float)k[12];
+            intr.tau_y = (float)k[13];
+
+            CALL_HAL(projectPoints, cv_hal_project_points_pinhole32f,
+                     (float*)objectPoints.data, objectPoints.step, count,
+                     (float*)ipoints.data, ipoints.step, rtMatrix, &intr);
+        }
+
+        if (objpt_depth == CV_64F && ipoints.type() == CV_64F)
+        {
+            double rtMatrix[12] = { R[0], R[1], R[2], t[0],
+                                    R[3], R[4], R[5], t[1],
+                                    R[6], R[7], R[8], t[2] };
+
+            cv_camera_intrinsics_pinhole_64f intr;
+            intr.fx = fx; intr.fy = fy;
+            intr.cx = cx; intr.cy = cy;
+            intr.amt_k = 0; intr.amt_p = 0; intr.amt_s = 0; intr.use_tau = false;
+
+            switch (ktotal)
+            {
+            case  0: break;
+            case  4: // [k_1, k_2, p_1, p_2]
+                intr.amt_k = 2; intr.amt_p = 2;
+                break;
+            case  5: // [k_1, k_2, p_1, p_2, k_3]
+                intr.amt_k = 3; intr.amt_p = 2;
+                break;
+            case  8: // [k_1, k_2, p_1, p_2, k_3, k_4, k_5, k_6]
+                intr.amt_k = 6; intr.amt_p = 2;
+                break;
+            case 12: // [k_1, k_2, p_1, p_2, k_3, k_4, k_5, k_6, s_1, s_2, s_3, s_4]
+                intr.amt_k = 6; intr.amt_p = 2; intr.amt_s = 4;
+                break;
+            case 14: // [k_1, k_2, p_1, p_2, k_3, k_4, k_5, k_6, s_1, s_2, s_3, s_4, tau_x, tau_y]
+                intr.amt_k = 6; intr.amt_p = 2; intr.amt_s = 4; intr.use_tau = true;
+                break;
+            default:
+                CV_Error(cv::Error::StsInternal, "Wrong number of distortion coefficients");
+            }
+
+            intr.k[0] = k[0];
+            intr.k[1] = k[1];
+            intr.k[2] = k[4];
+            intr.k[3] = k[5];
+            intr.k[4] = k[6];
+            intr.k[5] = k[7];
+
+            intr.p[0] = k[2];
+            intr.p[1] = k[3];
+
+            for (int ctr = 0; ctr < 4; ctr++)
+            {
+                intr.s[ctr] = k[8+ctr];
+            }
+
+            intr.tau_x = k[12];
+            intr.tau_y = k[13];
+
+            CALL_HAL(projectPoints, cv_hal_project_points_pinhole64f,
+                     (double*)objectPoints.data, objectPoints.step, count,
+                     (double*)ipoints.data, ipoints.step, rtMatrix, &intr);
+        }
+    }
+
+    Mat matM(objectPoints.size(), CV_64FC(objpt_cn));
+    objectPoints.convertTo(matM, CV_64F);
+    ipoints.convertTo(_m, CV_64F);
+    const Point3d* M = matM.ptr<Point3d>();
+    Point2d* m = _m.ptr<Point2d>();
+
     for( i = 0; i < count; i++ )
     {
         double X = M[i].x, Y = M[i].y, Z = M[i].z;
```
@savuor please review the proposed change.

2024-06-26 12:30 UTC, mshabunin commented
@asmorkalov , I've added fix for `projectPoints`.

2024-06-26 14:43 UTC, asmorkalov approved these changes
:+1:

2024-06-27 15:39 UTC, merged