Add yolov8l.onnx to samples
opencv/opencv pull request #25775
Opened 2024-06-17 18:25 UTC by richard28039

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

Hello, I noticed that the /samples/dnn/models.yml said it should be used for all yolov8 models, but the YOLOv8l is not Included in the file, so I added it to the file, thanks.
![image](https://github.com/opencv/opencv/assets/89371302/7a7b0090-ef4c-478d-8f24-7d99260fe0c9)

2024-06-18 07:44 UTC, asmorkalov commented
We already have several yolov8 models in samples. We do not need yet another one, if it just brings fatter backbone, but not some DNN features.

2024-06-18 07:59 UTC, Tsai-chia-hsiang commented
But we think the model.yml file.

https://github.com/opencv/opencv/blob/24907f35a32b75d9c5b34a203b44327ba53f86f4/samples/dnn/models.yml#L22

It says that it supports the YOLOv8L model, but there is no link for the YOLOv8L model.
Thus, it's better to support YOLOv8L to satisfy what Line 22 says. 

Thanks!

2024-06-21 14:17 UTC, asmorkalov requested changes

2024-06-21 14:17 UTC, asmorkalov commented on samples/dnn/models.yml
> +yolov8l:
```
opencv-master/samples/dnn$ python3 ./download_models.py yolov8l
DownloadInstance <opencv_face_detector_fp16>
DownloadInstance <opencv_face_detector_uint8>
DownloadInstance <opencv_fd>
DownloadInstance <yolov8x>
DownloadInstance <yolov8s>
DownloadInstance <yolov8n>
DownloadInstance <yolov8m>
DownloadInstance <yolov8l>
Model: yolov8l
  Working on yolov8l
  Getting file yolov8l.onnx
  expected SHA1: 5c5cc8ad7ab50973a84444bae4e613065a479ea1
  there is already a file with the same name
  actual SHA1:462df53ca3a85d110bf6be7fc2e2bb1277124395
  hash didn't match, loading file
  hash check failed - loading
  Preparing to download file yolov8l.onnx
  expected SHA1: 5c5cc8ad7ab50973a84444bae4e613065a479ea1
  there is already a file with the same name
  actual SHA1:462df53ca3a85d110bf6be7fc2e2bb1277124395
  200 OK [166.78626346588135 Mb]
  progress >>>>>>>>>>>>>>>>>  Downloaded yolov8l.onnx with size 166.78626346588135 Mb
  expected SHA1: 5c5cc8ad7ab50973a84444bae4e613065a479ea1
  there is already a file with the same name
  actual SHA1:462df53ca3a85d110bf6be7fc2e2bb1277124395
  There was some problem with loading file yolov8l.onnx for yolov8l
  Exception: Hash mismatch: expected 5c5cc8ad7ab50973a84444bae4e613065a479ea1 vs actual of 462df53ca3a85d110bf6be7fc2e2bb1277124395
```

2024-06-21 15:12 UTC, asmorkalov commented
Looks like the model was exported with another parameters than all other yolos we have in the sample. The sample generate a lot of garbage boxes that do not correspond to real objects. Command for the sample: `./bin/example_dnn_yolo_detector --model=./yolov8l.onnx --yolo=yolov8`

2024-06-21 16:21 UTC, richard28039 commented
Hi, the ```mode.yml``` scale is 0.0039, and it's necessary to give this argument.

If not passing --scale = 0.0039:
```
./yolo_detecor --input=./261902.jpg --yolo=yolov8 --model=./yolov8l.onnx 
```
The result of yolo_detecor.cpp is

![testyolov8l_no_scale](https://github.com/opencv/opencv/assets/89371302/906046a2-f6cf-4e09-8bbe-c89fa37202dc)

After passing --scale = 0.0039
```
./yolo_detecor --input=./261902.jpg --yolo=yolov8 --model=./yolov8l.onnx  --scale=0.0039 
```
The result becomes:

![testyolov8l_with_scale](https://github.com/opencv/opencv/assets/89371302/17d9ef74-b3ba-431d-a038-45c463f1413c)

Please take a look, Thanks!

2024-06-22 09:17 UTC, richard28039 commented
Hello, I found some mistakes when testing, so I removed the unnecessary whitespace in line92 and pushed the new commit; thanks.
```
Samples/dnn/models.yml:92: trailing whitespace.
```

2024-06-22 15:52 UTC, asmorkalov approved these changes

2024-06-24 07:28 UTC, merged