core: C-API cleanup: RNG algorithms in core
opencv/opencv pull request #26259
Opened 2024-10-05 08:23 UTC by Kumataro

close #26258 

- remove cvRandArr() and cvRandShuffle()
- remove CV_RAND_UNI and NORMAL

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

2024-10-06 13:41 UTC, mshabunin commented
I thought we are trying to preserve old functions and constants in 4.x. @asmorkalov , is it so?

2024-10-07 05:36 UTC, asmorkalov commented
@Kumataro Thanks for the contribution. The plan for today is following:
- Conservative policy in 4.x. We do not change C API, do not add tests and reduce usage internally.
- Remove C API completely in 5.x for the 5.0 release.

I propose the following steps:
- Apply all changes besides symbols removal to 4.x
- Merge 4.x to 5.x and remove symbols completely there. It makes 4.x-5.x merges simpler.

2024-10-07 11:20 UTC, Kumataro commented
OK, thank you for your reply !!

Currently I have no idea to fix this line. 
So the simplest fixing was "removing these functions", but they should be keeped at 4.x branch.
So I'll continue to try it (at 4.x).

```cpp
    cv::RNG& rng = _rng ? (cv::RNG&)*_rng : cv::theRNG();
```

2024-10-07 16:24 UTC, vpisarev approved these changes

2024-10-07 16:25 UTC, vpisarev requested changes
agree with @asmorkalov, the patch should be redirected to 5.x branch

2024-10-08 09:03 UTC, Kumataro commented
@mshabunin  Thank you for your advice, I updated with your suggest and it works well !!

2024-10-08 09:45 UTC, mshabunin approved these changes

2024-10-08 12:55 UTC, merged

2024-10-08 13:49 UTC, Kumataro commented
@asmorkalov Thank you very much for merging !!

At 5.x branch `cvRandArr()` and `cvRandShuffle()` had been removed at  https://github.com/opencv/opencv/commit/4f0fe1de960fd1084966c1e7fb45278cad3b38be .
So I think there are nothing to do for 5.x, we can close https://github.com/opencv/opencv/issues/26258