Cocoa/highgui: replace with `@autoreleasepool` blocks
opencv/opencv pull request #26660
Opened 2024-12-23 04:32 UTC by NekoAsakura

1. According to [Apple Developer Documentation](https://developer.apple.com/documentation/foundation/nsautoreleasepool#overview), `@autorelease` block is the preferred method over using an instance of NSAutoreleasePool directly. This is also discussed in https://github.com/opencv/opencv/pull/26625#discussion_r1886796039.

2. Starting from commit https://github.com/opencv/opencv/commit/4ec4cf687679cd39e154e00b349759f3885b95ab, `highgui_cocoa.mm` contained numerous debug lines that had been commented out, such as:
https://github.com/opencv/opencv/blob/dbb330d7be22b7d95dc2879f38cbe9816d47738a/modules/highgui/src/window_cocoa.mm#L172-L183
Such extraneous comments should be removed once debugging is complete and should not remain in the release environment. A previous commit https://github.com/opencv/opencv/commit/fb34f36c695c177d34b9303bd175925995cc3daf had partially cleaned up these comments. This PR made a thorough review and cleaned up the remaining extraneous comments.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ ] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

2025-01-10 09:53 UTC, VadimLevin requested changes

2025-01-10 09:53 UTC, VadimLevin commented on modules/highgui/src/window_cocoa.mm
> +        return res;
It seems like return is misplaced - it should be outside of the `@autoreleasepool` scope

2025-01-10 09:53 UTC, VadimLevin commented on modules/highgui/src/window_cocoa.mm
>      }
I think `autoreleasepool` should scope only `window` manipulation part
```objc
    if(name == NULL)
        CV_ERROR( CV_StsNullPtr, "NULL window name" );
    @autoreleasepool {
        CVWindow* window = cvGetWindow(name);
        if(window) {
            [window setMouseCallback:function];
            [window setMouseParam:info];
        }
    }
```

2025-01-10 09:53 UTC, VadimLevin commented on modules/highgui/src/window_cocoa.mm
> +    @autoreleasepool {
I think `autoreleasepool` should scope only `window` manipulation part
```objc
    if (window_name == NULL) {
        CV_ERROR( CV_StsNullPtr, "NULL window name" );
    }
    @autoreleasepool {
        CVWindow* window = cvGetWindow(window_name);
        if (window) {
            [window createSliderWithName:trackbar_name
                                maxValue:count
                                   value:val
                                callback:on_notify];
            result = 1;
        }
    }
```

2025-01-10 09:53 UTC, VadimLevin commented on modules/highgui/src/window_cocoa.mm
>      }
```objc
if (name == NULL) {
    CV_ERROR( CV_StsNullPtr, "NULL window name" );
}
@autoreleasepool {
        CVWindow *window = GetWindow(name);
```

2025-01-10 09:53 UTC, VadimLevin commented on modules/highgui/src/window_cocoa.mm
> +    @autoreleasepool{
I think `@autoreleasepool` block should include `CVWindow* window = cvGetWindow(name);` as it is done in other functions

2025-01-10 09:53 UTC, VadimLevin commented on modules/highgui/src/window_cocoa.mm
> +    @autoreleasepool{
I think `@autoreleasepool` block should include the whole function body, not only `NSString` creation

2025-01-10 09:53 UTC, VadimLevin commented on modules/highgui/src/window_cocoa.mm
> +    @autoreleasepool{
Please refer to the following guide on how to return object managed by autorelease pools: https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmAutoreleasePools.html
In particular, the example with `findMatchingObject` which is close to the use case

2025-01-11 13:40 UTC, NekoAsakura commented
Thank you for your time reviewing! I have made the suggested changes in the latest commit.

2025-01-11 15:11 UTC, asmorkalov commented
@VadimLevin please take a look again.

2025-01-15 14:31 UTC, NekoAsakura commented
Oops, some tests have failed. It seems this is due to accidental variable shadowing. I will correct it asap.

2025-01-15 21:06 UTC, opencv-alalek commented
CI logs:

```
modules/highgui/src/window_cocoa.mm:275: trailing whitespace.
+    
modules/highgui/src/window_cocoa.mm:799: trailing whitespace.
+        
```

https://github.com/opencv/opencv/wiki/How_to_contribute#q3-i-was-asked-to-remove-whitespace-issues-how-can-i-do-that

2025-01-16 03:42 UTC, NekoAsakura commented
Thank you :) it should have been fixed.

2025-01-24 07:38 UTC, VadimLevin approved these changes

2025-01-24 08:34 UTC, merged