Fix null pointer dereference in Tracklet by initializing rgb_feature
opencv/opencv pull request #26682
Opened 2024-12-29 22:33 UTC by 5usu

…_, adding AddRgbFeature(), and improving robustness in ComputeRgbDistance().

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ ] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

2024-12-30 06:59 UTC, 5usu commented
I'm testing locally right now will be pushing it again as it's done

2025-01-07 08:51 UTC, AumGupta approved these changes

2025-02-07 14:29 UTC, asmorkalov commented on modules/gapi/src/3rdparty/vasot/src/components/ot/test_tracklet.cpp
> +}
It's redundant most probably.

2025-02-07 14:29 UTC, asmorkalov commented
@dmatveev @TolyaTalamanov Friendly reminder.

2025-03-26 21:20 UTC, dmatveev commented
Thanks a lot @5usu ! I think @AsyaPronina is the right person to have a look here, I'll ask her to review the change.

2025-03-26 23:56 UTC, AsyaPronina requested changes

2025-03-28 02:04 UTC, AsyaPronina approved these changes

2025-03-28 04:59 UTC, 5usu commented
so this going to be merged?

2025-03-31 06:47 UTC, merged